# Generated by Django 2.2.7 on 2019-11-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subway',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subway',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
