# Generated by Django 2.2.7 on 2019-11-18 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_subway'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subway',
        ),
    ]
